/**
 * Font utility
 * ---------------------------------------------------------------------------
 * Verifies a TTF contains the glyphs we need (notably the Naira sign U+20A6,
 * which jsPDF's built-in WinAnsi fonts cannot render) and converts the font to
 * a base64 module for embedding into the PDF.
 *
 * Usage:
 *   node scripts/font-check.mjs verify .tmp-font.bin
 *   node scripts/font-check.mjs embed .tmp-font.bin src/fonts/noto-sans.js NotoSans
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

/** Parses the TTF table directory and returns { tag: offset }. */
function readTables(buf) {
  const numTables = buf.readUInt16BE(4);
  const tables = {};
  for (let i = 0; i < numTables; i += 1) {
    const rec = 12 + i * 16;
    tables[buf.toString('ascii', rec, rec + 4)] = buf.readUInt32BE(rec + 8);
  }
  return tables;
}

/** Extracts the set of code points covered by the font's cmap. */
function readCoverage(buf) {
  const tables = readTables(buf);
  if (tables.cmap === undefined) return new Set();
  const base = tables.cmap;
  const numSub = buf.readUInt16BE(base + 2);

  let best = null;
  for (let i = 0; i < numSub; i += 1) {
    const rec = base + 4 + i * 8;
    const platformId = buf.readUInt16BE(rec);
    const encodingId = buf.readUInt16BE(rec + 2);
    const subOffset = buf.readUInt32BE(rec + 4);
    const subBase = base + subOffset;
    const format = buf.readUInt16BE(subBase);
    // Prefer Windows full-repertoire (3,1) then Unicode BMP (3,10)/(0,x).
    const score =
      (platformId === 3 && encodingId === 10) ? 3
        : (platformId === 3 && encodingId === 1) ? 2
          : platformId === 0 ? 1 : 0;
    if (format === 4 && score > 0) {
      if (best === null || score > best.score) best = { subBase, score };
    }
  }
  if (best === null) return new Set();

  const sub = best.subBase;
  const segX2 = buf.readUInt16BE(sub + 6);
  const segCount = segX2 / 2;
  const endBase = sub + 14;
  const startBase = endBase + segX2 + 2;
  const deltaBase = startBase + segX2;
  const rangeBase = deltaBase + segX2;

  const points = new Set();
  for (let s = 0; s < segCount; s += 1) {
    const end = buf.readUInt16BE(endBase + s * 2);
    const start = buf.readUInt16BE(startBase + s * 2);
    if (start === 0xffff) continue;
    for (let cp = start; cp <= end && cp <= 0xffff; cp += 1) points.add(cp);
  }
  return points;
}

const [cmd, file, outFile, outName] = process.argv.slice(2);
if (!cmd || !file) {
  console.error('Usage: node scripts/font-check.mjs <verify|embed> <font.ttf> [out.js] [name]');
  process.exit(1);
}

const buf = readFileSync(file);
const coverage = readCoverage(buf);

// Everything the app actually prints: ASCII, common typographic punctuation,
// currency symbols, and the Naira sign.
const REQUIRED = [0x20a6, 0x2013, 0x2014, 0x20ac, 0x00a3, 0x2022, 0x2044];
const NAMES = {
  0x20a6: 'Naira sign ₦',
  0x2013: 'en dash',
  0x2014: 'em dash',
  0x20ac: 'Euro',
  0x00a3: 'Pound',
  0x2022: 'bullet',
  0x2044: 'fraction slash',
};

console.log(`Font: ${file} (${buf.length} bytes)`);
console.log(`Coverage: ${coverage.size} code points`);

let missing = 0;
REQUIRED.forEach((cp) => {
  const ok = coverage.has(cp);
  if (!ok) missing += 1;
  console.log(`  ${ok ? 'PASS' : 'FAIL'}  U+${cp.toString(16).toUpperCase().padStart(4, '0')}  ${NAMES[cp]}`);
});

// Latin letters/digits are assumed; spot-check a few.
['A', 'a', '0', ' '].forEach((ch) => {
  const ok = coverage.has(ch.codePointAt(0));
  if (!ok) missing += 1;
  console.log(`  ${ok ? 'PASS' : 'FAIL'}  basic glyph "${ch}"`);
});

if (missing > 0) {
  console.error(`\n${missing} required glyph(s) missing`);
  process.exit(1);
}

console.log('\nAll required glyphs present.');

if (cmd === 'embed') {
  if (!outFile) {
    console.error('embed requires an output path');
    process.exit(1);
  }
  mkdirSync(dirname(outFile), { recursive: true });
  const name = outName || 'EmbeddedFont';
  const b64 = buf.toString('base64');
  const module = `/**
 * ${name} — embedded for jsPDF
 * ---------------------------------------------------------------------------
 * Noto Sans, SIL Open Font License 1.1.
 * Embedded because jsPDF's built-in fonts are limited to the WinAnsi (CP-1252)
 * character set, which does not include the Naira sign (U+20A6). Without this,
 * every currency figure in the exported PDF loses its ₦ symbol.
 *
 * Generated by scripts/font-check.mjs — do not edit by hand.
 */

/** Base64-encoded TTF bytes. */
export const ${name.toUpperCase()}_BASE64 =
  '${b64}';

/** Filename jsPDF registers the font under. */
export const ${name.toUpperCase()}_FILE = '${name}.ttf';

/**
 * Registers the font with a jsPDF document and selects it for all text.
 * Falls back to "NGN" substitution if the font cannot be embedded, so a broken
 * asset degrades the currency prefix rather than the whole document.
 */
export function applyNairaFont(doc) {
  try {
    doc.addFileToVFS(${name.toUpperCase()}_FILE, ${name.toUpperCase()}_BASE64);
    doc.addFont(${name.toUpperCase()}_FILE, '${name}', 'normal');
    doc.addFont(${name.toUpperCase()}_FILE, '${name}', 'bold');
    doc.setFont('${name}', 'normal');
    return true;
  } catch (err) {
    console.warn('Falling back to NGN prefix:', err && err.message);
    return false;
  }
}
`;
  writeFileSync(outFile, module);
  console.log(`\nWrote ${outFile} (${Math.round(b64.length / 1024)} KB base64)`);
}
