"""Subset the embedded PDF font to only the characters SolarQuote NG prints.

Why: the full Noto Sans TTF is 569KB and jsPDF embeds it into EVERY generated
document TWICE (once registered as 'normal', once as 'bold'). Measured on the
generate button that cost 312-402ms of synchronous main-thread work and 13-17MB
of heap per document, which is what froze and then whited-out the Android
WebView. The document only ever needs ASCII plus a handful of marks.

Run:  python scripts/subset_font.py
Writes src/fonts/noto-sans-subset.js and its .ttf next to it.
"""
import os
import sys

try:
    from fontTools import subset
    from fontTools.ttLib import TTFont
except ImportError:
    sys.exit("fontTools is required: pip install fonttools")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_TTF = os.path.join(ROOT, "assets", "fonts-src", "NotoSans-Regular.ttf")
OUT_TTF = os.path.join(ROOT, "src", "fonts", "noto-sans-subset.ttf")
OUT_JS = os.path.join(ROOT, "src", "fonts", "noto-sans-subset.js")
SRC_TTF_BOLD = os.path.join(ROOT, "assets", "fonts-src", "NotoSans-Bold.ttf")
OUT_TTF_BOLD = os.path.join(ROOT, "src", "fonts", "noto-sans-subset-bold.ttf")

# Every character the PDF generator can emit: printable ASCII, the Naira sign,
# common typographic marks used in headings and bullets, and the Latin-1 range
# used for stray accented names a client may type.
CHARS = "".join(chr(c) for c in range(0x20, 0x7F))
CHARS += (
    "\u20A6"  # Naira sign - the whole reason this font exists
    "\u00A0\u00A3\u00B0\u00B7\u00B2\u00B5\u00D7\u2013\u2014\u2018\u2019"
    "\u201C\u201D\u2022\u2026\u2022\u00A9\u00AE\u2122"
    "\u00E0\u00E1\u00E2\u00E4\u00E8\u00E9\u00EA\u00EB\u00ED\u00F1\u00F4"
    "\u00F6\u00F9\u00FC"
)


def subset_one(src_ttf: str, out_ttf: str) -> tuple:
    """Subsets one weight and returns (raw_bytes, glyph_count)."""
    font = TTFont(src_ttf)
    options = subset.Options()
    # Keep the file valid for jsPDF, which needs TrueType outlines, a cmap and
    # correct metrics. Drop everything else.
    options.layout_features = []
    options.name_IDs = [1, 2, 3, 4, 6]
    options.name_legacy = True
    options.notdef_outline = True
    options.recalc_bounds = True
    options.drop_tables += ["DSIG"]
    options.glyph_names = False
    options.hinting = False
    options.desubroutinize = True

    subsetter = subset.Subsetter(options=options)
    subsetter.populate(text=CHARS)
    subsetter.subset(font)

    cmap = font.getBestCmap() or {}
    # U+20A6 must survive or the whole exercise is pointless.
    if 0x20A6 not in cmap:
        sys.exit(f"FATAL: the Naira sign was dropped from {src_ttf}")
    if 0x41 not in cmap or 0x30 not in cmap:
        sys.exit(f"FATAL: basic Latin was dropped from {src_ttf}")

    font.save(out_ttf)
    return open(out_ttf, "rb").read(), len(cmap)


def main() -> int:
    if not os.path.exists(SRC_TTF):
        sys.exit(f"source font not found: {SRC_TTF}")

    regular_bytes, glyphs = subset_one(SRC_TTF, OUT_TTF)

    # A real bold weight keeps the PDF's heading hierarchy. The previous build
    # faked it by registering the SAME regular bytes as 'bold', which doubled the
    # embedded font for zero visual gain - that was the /FontFile2 count of 2.
    bold_bytes = b""
    if os.path.exists(SRC_TTF_BOLD):
        bold_bytes, _ = subset_one(SRC_TTF_BOLD, OUT_TTF_BOLD)

    import base64

    b64 = base64.b64encode(regular_bytes).decode("ascii")
    b64_bold = base64.b64encode(bold_bytes).decode("ascii") if bold_bytes else ""
    original = os.path.getsize(SRC_TTF)

    bold_js = ""
    if b64_bold:
        bold_js = f'''
/** Real bold weight, subsetted identically. Keeps heading weight in the PDF. */
export const NOTOSANS_BOLD_BASE64 =
  '{b64_bold}';

export const NOTOSANS_BOLD_FILE = 'NotoSansSub-Bold.ttf';
'''

    bold_reg = (
        "    doc.addFileToVFS(NOTOSANS_BOLD_FILE, NOTOSANS_BOLD_BASE64);\n"
        "    doc.addFont(NOTOSANS_BOLD_FILE, 'NotoSans', 'bold');"
        if b64_bold
        else ""
    )

    module = f'''/**
 * NotoSans (subset) - embedded for jsPDF
 * ---------------------------------------------------------------------------
 * Noto Sans, SIL Open Font License 1.1. Reduced to the {len(CHARS)} characters
 * this app can actually print, so the Naira sign (U+20A6) survives into the
 * exported PDF without shipping a 569KB font in every APK.
 *
 * The unsubsetted font was embedded into every document and its regular bytes
 * were registered a second time as 'bold', costing 13-17MB of heap and
 * 300-400ms of main-thread time per generation. That is what froze and then
 * whited-out the Android WebView. These files are {len(regular_bytes)} and
 * {len(bold_bytes)} bytes instead of {original}.
 *
 * GENERATED by scripts/subset_font.py - do not edit by hand.
 * Re-generate with:  npm run font:subset
 */

export const NOTOSANS_BASE64 =
  '{b64}';

export const NOTOSANS_FILE = 'NotoSansSub.ttf';
{bold_js}
/** Glyphs the subset is guaranteed to cover, asserted by scripts/font-check.mjs. */
export const NOTOSANS_CODEPOINTS = [
  0x20a6, // Naira sign
  0x2013, 0x2014, // en / em dash
  0x2018, 0x2019, 0x201c, 0x201d, // quotes
  0x2022, 0x2026, 0x00b7, 0x00b2, // bullet, ellipsis, middot, superscript 2
  0x00a3, 0x00a9, 0x00ae, 0x2122, // pound, copyright, registered, trademark
  0x00a0, 0x00d7, // nbsp, times
];

/**
 * Registers the subset font(s) with a jsPDF document and selects the regular
 * weight. Returns true when the font is usable, so a failed embed can fall back
 * to an "NGN" prefix rather than silently dropping every currency symbol.
 */
export function applyNairaFont(doc) {{
  try {{
    doc.addFileToVFS(NOTOSANS_FILE, NOTOSANS_BASE64);
    doc.addFont(NOTOSANS_FILE, 'NotoSans', 'normal');
{bold_reg}
    doc.setFont('NotoSans', 'normal');
    return true;
  }} catch (err) {{
    console.warn('Falling back to NGN prefix:', err && err.message);
    return false;
  }}
}}
'''
    with open(OUT_JS, "w", encoding="utf-8") as fh:
        fh.write(module)

    print(f"subset regular: {original} -> {len(regular_bytes)} bytes ({100 * len(regular_bytes) / original:.1f}%)")
    if bold_bytes:
        ob = os.path.getsize(SRC_TTF_BOLD)
        print(f"subset bold:    {ob} -> {len(bold_bytes)} bytes ({100 * len(bold_bytes) / ob:.1f}%)")
    else:
        print("subset bold:    (source absent, headings use the regular weight)")
    print(f"glyphs kept:    {glyphs}")
    print(f"total shipped:  {len(regular_bytes) + len(bold_bytes)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
